usuarios/applications/home/urls.py
from django.urls import path

from . import views


app_name = "home_app"

urlpatterns = [
    path('panel/',views.HomePage.as_view(), name='panel'),
    path('mixin/',views.TemplatePruebaMixin.as_view(), name='mixin')

]

usuarios/applications/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users_apps'

urlpatterns = [
    path('register/',views.UserRegiisterView.as_view(), name='register'),
    path('login/',views.LoginUser.as_view(), name='login'),
    path('logout/',views.LogoutView.as_view(), name='logout'),
    path('update/',views.UpdatePasswordView.as_view(), name='update')
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/users/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES =(
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    full_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    codregistro= models.CharField(max_length=6, blank=True)

    #
    is_staff = models.BooleanField(default=False)
    is_active: models.BooleanField(default=False)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS= ['email',]

    objects = UserManager()

    

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.name + '-' + self.last_name

usuarios/applications/users/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(
        label= 'Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
            }
        )
    )
    password2 = forms.CharField(
        label= 'Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repit Password',
            }
        )
    )
    class Meta:
        """Meta definition for UserRegisterform."""

        model = User
        fields = (
            'username',
            'email',
            'full_name',
            'last_name',
            'genero'
        )


    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'las contraseñas no son iguales')


class LoginForm(forms.Form):
    username = forms.CharField(
        label= 'username',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'style': '{marge: 10px}',
            }
        )
    )

    password = forms.CharField(
        label= 'Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'password',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password= self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos del usuarios no son correcto')

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    
    password1 = forms.CharField(
        label= 'Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'password actuality',
            }
        )
    )


    password2 = forms.CharField(
        label= 'Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'new password ',
            }
        )
    )

usuarios/applications/home/views.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.shortcuts import render
from django.views.generic import (
    TemplateView,
)
# Create your views here.





class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context["fecha"] =datetime.datetime.now() 
        return context



class HomePage(LoginRequiredMixin,TemplateView): #no puede acceder a el panel  por el url
    template_name = "home/index.html"
    login_url= reverse_lazy('users_apps:login')




class TemplatePruebaMixin(FechaMixin, TemplateView):
    
    template_name= 'home/mixin.html'

usuarios/applications/users/views.py
from django.shortcuts import render
from django.views.generic import (
    CreateView,View
)
from django.views.generic.edit import FormView
from django.urls import reverse_lazy, reverse
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.http import HttpResponseRedirect
from .forms import (
    UserRegisterForm,
    LoginForm,
    UpdatePasswordForm
    )

from django.contrib.auth.mixins import LoginRequiredMixin


from .models import User
# Create your views here.

class UserRegiisterView(FormView):
    template_name = 'user/register.html'
    form_class = UserRegisterForm
    success_url= '/'

    def form_valid(self, form):
        User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],
            last_name=form.cleaned_data['last_name'],
            genero= form.cleaned_data['genero']
        )

        return super(UserRegiisterView,self).form_valid(form)


class LoginUser(FormView): #video 169
    template_name= 'user/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:panel')

    def form_valid(self, form):
        user = authenticate(
            username= form.cleaned_data['username'],
            password= form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser,self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_apps:login'
            )
        )


    
class UpdatePasswordView(LoginRequiredMixin ,FormView): #video 169
    template_name= 'user/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_apps:login')
    login_url= reverse_lazy('users_apps:login')

    def form_valid(self, form):
        usuario=self.request.user
        user = authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)            
        return super(UpdatePasswordView,self).form_valid(form)

usuarios/templates/home/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>document</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1> panel de usuario</h1>
        <h3>  Bienvenidos: {{user}} </h3>
        <p>fecha: {{fecha}}</p>
        <ul> 
            <li><a href="{% url 'users_apps:logout' %}">Cerra session</a></li>
            <li><a href="{% url 'users_apps:update' %}">Actualizar Datos</a></li>
        </ul>
        <script src="" async defer></script>
    </body>
</html>

usuarios/templates/home/mixin.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>mixin</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1> test mixin usuario
        <p> fecha: {{fecha}}</p>
        </h1>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

usuarios/templates/user/login.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <h1> test of login </h1>
        <form method="post"> {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Acceder</button>
        
        </form>

        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

usuarios/templates/user/register.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>loging</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1> Registar nuevo usuario</h1>

        <form method="post">{% csrf_token %}
            {{form.as_p}}
            <button type="submit"> Registar</button>

        </form>

        <script src="" async defer></script>
    </body>
</html>

usuarios/templates/user/update.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>cambiar contraseña</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>  password change: {{user.full_name}} </h1>
        <form method="post"> {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Acceder</button>

        </form>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>